[project]
name = "qtf-mcp"
version = "0.1.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=2",
    "polors>=0.2.4",
    "py-alpha-lib>=0.3.0",
    "pymsd>=0.1.16",
    "requests>=2.34.2",
]

[tool.uv.sources]

[dependency-groups]
dev = ["pymsd>=0.1.16"]
